name: esy

on: [push, pull_request]

jobs:
  native:
    name: Build for Native

    strategy:
      matrix:
        system: [ubuntu, macos]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - name: Create esy wrapper
        run: |
          echo '{
            "name": "cross-compile",
            "dependencies": {
              "ocaml": "4.12.x",
              "@opam/mirage-clock": "*",
              "@opam/mirage-clock-unix": "*",
              "@opam/mirage-clock-solo5": "*",
              "reason-mobile": "github:EduardoRFS/reason-mobile:generate.json#7ba258319b87943d2eb0d8fb84562d0afeb2d41f"
            },
            "resolutions": {
              "@opam/mirage-clock": "./mirage-clock.opam",
              "@opam/mirage-clock-unix": "./mirage-clock-unix.opam",
              "@opam/mirage-clock-solo5": "./mirage-clock-solo5.opam"
            }
          }' > esy.json

      - name: Generate esy lock
        run: esy solve

      - uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

